mysql:
  image: mysql:5.6.26
  environment:
   - MYSQL_ROOT_PASSWORD=root
  command: "mysql -uroot -proot < createDB.sql"
  volume:
    - srv/owncloud/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
